title: Extended Virtue
author: Duygu Uygun-Tunç
email: duygu.uygun@outlook.com
description: > # this means to ignore newlines until "baseurl:"
I'm Duygu Uygun-Tunç. I am a philosopher interested in the epistemology of science. I currently work on the project Extended Scientific Virtue funded by the Turkish Scientific and Technological Research
Council (TUBITAK) and the European Commission under the Horizon 2020 Marie Skłodowska-Curie Actions Cofund program “Co-Funded Brain
Circulation2 Scheme” at the Middle-East Technical University (METU).
# social links
twitter_username: uygun_tunc # DO NOT include the @ character, or else the build will fail!
github_username:  DuyguUygun # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
